### ISSUE TITLE
"a valid android sdk path is required in editor settings" error on export dialog - godot 3.4

### ISSUE THREAD

**Issue by d8sconz** [abarichello/godot-ci#68] opened 2021-12-06 03:06 UTC
Linux Mint 20
Godot 3.4

Just upgraded and can't do anything to correct this error message. The SDK path is in Editor settings, it's the correct path and I've tried several alternative paths to no avail.

**Comment by Foxomat** [comment] 2021-12-06 13:51
having the same problem on windows with godot 3.4

@d8sconz Editor settings is independent form your project so your personal Editor settings should not matter for the android export pipeline. I suppose that this is not on our side to fix.

**Comment by Foxomat** [comment] 2021-12-06 13:52
also just noticed this is a duplicate of #59

**Comment by Calinou** [comment] 2021-12-06 14:08
Duplicate of https://github.com/abarichello/godot-ci/issues/59.

**Closed by Calinou** 2021-12-06 14:08 UTC

**Comment by d8sconz** [comment] 2021-12-06 22:25
But it was working yesterday on 3.2? Nothing has changed on my side.

**Comment by Calinou** [comment] 2021-12-06 22:27
Godot 3.3 and later changed the location of Android settings. There is no more need to set the **Adb** and **Jarsigner** settings. Instead, you set the **Android Sdk Path** setting which will control both the ADB and jarsigner paths behind the scenes.

**Comment by d8sconz** [comment] 2021-12-06 22:35
I have set the SDK path. It is the correct path. I still get the error. I
have removed the Adb and Jarsigner entries. Error remains

**Comment by realkotob** [comment] 2022-12-25 08:50
Pull Requests are welcome for this 👍

**Comment by Sam2much96** [comment] 2023-09-29 08:28
The same issue is present in docker image: barichello/godot-ci:3.5.2
