### ISSUE TITLE
Tag 4.0.2 does not exist (anymore?) on docker hub

### ISSUE THREAD

**Issue by axeldeau** [abarichello/godot-ci#109] opened 2023-05-05 03:52 UTC
Thanks for this amazing repo, hoping to leverage it's power during the [GoGodotJam](https://itch.io/jam/go-godot-jam-4) tomorrow

On a Gitlab-ci run the runner complains about the missing tag:

<img width="1907" alt="image" src="https://user-images.githubusercontent.com/2110938/236374787-98ecd520-6080-435a-9c83-306f1bebbffb.png">

See [Docker hub tags list](https://hub.docker.com/r/barichello/godot-ci/tags)

**Comment by Calinou** [comment] 2023-05-05 14:31
- Duplicate of https://github.com/abarichello/godot-ci/issues/98. This probably won't be done by tomorrow, sorry.

**Closed by Calinou** 2023-05-05 14:31 UTC

**Comment by axeldeau** [comment] 2023-05-05 20:21
Hey that's fine, I plan to use this one instead `adrasteondev/godot-ci:4.0.2` not sure if it will work, worst can I'll generate the build manually
